// contestLeaderboardData.js

const contestLeaderboardData = [
    // Round 1 - 8 participants
    {
        name: "Aarav Patel",
        rank: 1,
        score: 980,
        round: "round1",
        matchTime: "00:30:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg?nat=in",
    },
    {
        name: "Vihaan Sharma",
        rank: 2,
        score: 950,
        round: "round1",
        matchTime: "00:32:10",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg?nat=in",
    },
    {
        name: "Advait Singh",
        rank: 3,
        score: 920,
        round: "round1",
        matchTime: "00:35:20",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/3.jpg?nat=in",
    },
    {
        name: "Ananya Gupta",
        rank: 4,
        score: 900,
        round: "round1",
        matchTime: "00:37:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/women/1.jpg?nat=in",
    },
    {
        name: "Ishaan Kumar",
        rank: 5,
        score: 870,
        round: "round1",
        matchTime: "00:40:00",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/4.jpg?nat=in",
    },
    {
        name: "Saanvi Reddy",
        rank: 6,
        score: 850,
        round: "round1",
        matchTime: "00:42:15",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/women/2.jpg?nat=in",
    },
    {
        name: "Arjun Choudhary",
        rank: 7,
        score: 830,
        round: "round1",
        matchTime: "00:44:30",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/5.jpg?nat=in",
    },
    {
        name: "Diya Mehta",
        rank: 8,
        score: 810,
        round: "round1",
        matchTime: "00:46:50",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/women/3.jpg?nat=in",
    },

    // Semi-final - 4 participants
    {
        name: "Aarav Patel",
        rank: 1,
        score: 980,
        round: "semi-final",
        matchTime: "00:30:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg?nat=in",
    },
    {
        name: "Vihaan Sharma",
        rank: 2,
        score: 950,
        round: "semi-final",
        matchTime: "00:32:10",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg?nat=in",
    },
    {
        name: "Advait Singh",
        rank: 3,
        score: 920,
        round: "semi-final",
        matchTime: "00:35:20",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/3.jpg?nat=in",
    },
    {
        name: "Ananya Gupta",
        rank: 4,
        score: 900,
        round: "semi-final",
        matchTime: "00:37:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/women/1.jpg?nat=in",
    },

    // Final - 2 participants
    {
        name: "Aarav Patel",
        rank: 1,
        score: 980,
        round: "final",
        matchTime: "00:30:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg?nat=in",
    },
    {
        name: "Vihaan Sharma",
        rank: 2,
        score: 950,
        round: "final",
        matchTime: "00:32:10",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg?nat=in",
    },

    // Winner - 1 participant
    {
        name: "Aarav Patel",
        rank: 1,
        score: 980,
        round: "winner",
        matchTime: "00:30:45",
        countdown: "05:00:00",
        avatar: "https://randomuser.me/api/portraits/men/1.jpg?nat=in",
    },
];

export default contestLeaderboardData;
